services:
  web:
    image: nginx:1.27-alpine
    container_name: gewulogic-site
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      # 同时支持 ww 和 www 域名
      - "traefik.http.routers.gewulogic-site.rule=Host(`ww.gewulogic.com`) || Host(`www.gewulogic.com`)"
      # 根据你的 traefik 配置，入口点为 https
      - "traefik.http.routers.gewulogic-site.entrypoints=https"
      - "traefik.http.routers.gewulogic-site.tls=true"
      # 证书解析器使用你配置好的 le
      - "traefik.http.routers.gewulogic-site.tls.certresolver=le"
      - "traefik.http.services.gewulogic-site.loadbalancer.server.port=80"
    restart: unless-stopped

networks:
  traefik-public:
    external: true
