services:
  web:
    image: nginx:1.27-alpine
    container_name: gewulogic-site
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gewulogic-site.rule=Host(`ww.gewulogic.com`)"
      - "traefik.http.routers.gewulogic-site.entrypoints=websecure"
      - "traefik.http.routers.gewulogic-site.tls=true"
      - "traefik.http.services.gewulogic-site.loadbalancer.server.port=80"
    restart: unless-stopped

networks:
  traefik-public:
    external: true
